spring.application.name=splunk

# MySQL datasource
# Assumption: database name is `splunk` on localhost:3306
spring.datasource.url=jdbc:mysql://localhost:3306/Splunk
spring.datasource.username=root
spring.datasource.password=Ggop1810
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
server.port=8010

# Logging Configuration
logging.level.root=INFO
logging.level.com.example.splunk=DEBUG
logging.level.com.splunk.logging=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
logging.file.name=logs/splunk-app.log

# Splunk HEC Configuration
splunk.hec.url=https://localhost:8088/services/collector
splunk.hec.token=9d6dc1d9-6cc3-49b1-a8c9-0fe52832a12b

